spring:
  application:
    name: operation-quasar

server:
  port: 8080

satellite:
  position:
    kenobi:
      x: -500
      y: -200
    skywalker:
      x: 100
      y: -100
    sato:
      x: 500
      y: 100
